spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/aventus"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

server:
  upload:
    dir: "upload/"
  base:
    url: "http://localhost:8080"
